version: "3"

services:
  api:
    build: .
    restart: always
    ports:
      - "8081:8081"
    depends_on:
      - db
  db:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3306:3306"
    container_name: mysql_db
    environment:
      MYSQL_DATABASE: "db"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "password"
      MYSQL_ROOT_PASSWORD: "password"
    volumes:
      - "./var/mysql:/var/lib/mysql"
      - "./ops/database:/docker-entrypoint-initdb.d"
      - "./var/log/mysql:/var/log/mysql"
  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - db
